CREATE TABLE IF NOT EXISTS public.visit_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL,
  solicitante text,
  data_visita date,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  rep_in_codigo integer,
  
  cliente_nome text,
  cnpj text,
  cidade text,
  estado text,
  transportadora text,
  
  contato_tecnico_nome text,
  contato_tecnico_depto text,
  contato_tecnico_email text,
  contato_tecnico_fone text,
  
  contato_comprador_nome text,
  contato_comprador_email text,
  contato_comprador_fone text,
  
  contato_gerente_nome text,
  contato_gerente_email text,
  contato_gerente_fone text,
  
  contato_coordenador_nome text,
  contato_coordenador_email text,
  contato_coordenador_fone text,
  
  contato_engenheiro_nome text,
  contato_engenheiro_email text,
  contato_engenheiro_fone text,

  marca_fabricante text,
  material_placas text,
  temperatura text,
  equipamento text,
  dimensoes text,
  ph_agua_lavagem text,
  qtde_placas text,
  ph text,
  produto_filtrar text,
  tempo_secagem text,
  percent_solidos text,
  tempo_filtracao text,
  tipo_abertura text,
  tipo_limpeza text,
  tipo_bomba text,
  qtde_setores text,
  pressao_sopro text,
  umidade_torta text,
  pressao_filtracao text,
  aux_filtracao text,

  tipo_linha_linhas text,
  medidas_obtidas_da text,
  fonte_medidas text,
  modelo_placa text,
  pinos_superiores_tipo text,
  pinos_superiores_qtd text,
  pinos_superiores_diametro text,
  pinos_superiores_distancias text,
  alimentacao_tipo text,
  amarracoes_superior text,
  amarracoes_inferior text,
  amarracoes_lateral text,
  vedacao_tipo text,
  vedacao_material text,
  cabeceiras_inicial text,
  cabeceiras_final text,

  motivo_substituicao text,
  tecido_atual text,
  cfm text,
  fornecedor_atual text,
  vida_util text,
  data_ultima_compra text,
  valor_pago text,
  situacao_lonas text,
  previsao_compra text,

  observacoes text,
  acoes text,
  medidas_desenho jsonb
);
