ALTER TABLE public.visit_reports 
  ADD COLUMN IF NOT EXISTS cliente_nome text,
  ADD COLUMN IF NOT EXISTS cnpj text,
  ADD COLUMN IF NOT EXISTS cidade text,
  ADD COLUMN IF NOT EXISTS estado text,
  ADD COLUMN IF NOT EXISTS transportadora text,
  
  ADD COLUMN IF NOT EXISTS contato_tecnico_nome text,
  ADD COLUMN IF NOT EXISTS contato_tecnico_depto text,
  ADD COLUMN IF NOT EXISTS contato_tecnico_email text,
  ADD COLUMN IF NOT EXISTS contato_tecnico_fone text,
  
  ADD COLUMN IF NOT EXISTS contato_comprador_nome text,
  ADD COLUMN IF NOT EXISTS contato_comprador_email text,
  ADD COLUMN IF NOT EXISTS contato_comprador_fone text,
  
  ADD COLUMN IF NOT EXISTS contato_gerente_nome text,
  ADD COLUMN IF NOT EXISTS contato_gerente_email text,
  ADD COLUMN IF NOT EXISTS contato_gerente_fone text,
  
  ADD COLUMN IF NOT EXISTS contato_coordenador_nome text,
  ADD COLUMN IF NOT EXISTS contato_coordenador_email text,
  ADD COLUMN IF NOT EXISTS contato_coordenador_fone text,
  
  ADD COLUMN IF NOT EXISTS contato_engenheiro_nome text,
  ADD COLUMN IF NOT EXISTS contato_engenheiro_email text,
  ADD COLUMN IF NOT EXISTS contato_engenheiro_fone text,

  ADD COLUMN IF NOT EXISTS marca_fabricante text,
  ADD COLUMN IF NOT EXISTS material_placas text,
  ADD COLUMN IF NOT EXISTS temperatura text,
  ADD COLUMN IF NOT EXISTS equipamento text,
  ADD COLUMN IF NOT EXISTS dimensoes text,
  ADD COLUMN IF NOT EXISTS ph_agua_lavagem text,
  ADD COLUMN IF NOT EXISTS qtde_placas text,
  ADD COLUMN IF NOT EXISTS ph text,
  ADD COLUMN IF NOT EXISTS produto_filtrar text,
  ADD COLUMN IF NOT EXISTS tempo_secagem text,
  ADD COLUMN IF NOT EXISTS percent_solidos text,
  ADD COLUMN IF NOT EXISTS tempo_filtracao text,
  ADD COLUMN IF NOT EXISTS tipo_abertura text,
  ADD COLUMN IF NOT EXISTS tipo_limpeza text,
  ADD COLUMN IF NOT EXISTS tipo_bomba text,
  ADD COLUMN IF NOT EXISTS qtde_setores text,
  ADD COLUMN IF NOT EXISTS pressao_sopro text,
  ADD COLUMN IF NOT EXISTS umidade_torta text,
  ADD COLUMN IF NOT EXISTS pressao_filtracao text,
  ADD COLUMN IF NOT EXISTS aux_filtracao text,

  ADD COLUMN IF NOT EXISTS tipo_linha_linhas text,
  ADD COLUMN IF NOT EXISTS medidas_obtidas_da text,
  ADD COLUMN IF NOT EXISTS fonte_medidas text,
  ADD COLUMN IF NOT EXISTS modelo_placa text,
  ADD COLUMN IF NOT EXISTS pinos_superiores_tipo text,
  ADD COLUMN IF NOT EXISTS pinos_superiores_qtd text,
  ADD COLUMN IF NOT EXISTS pinos_superiores_diametro text,
  ADD COLUMN IF NOT EXISTS pinos_superiores_distancias text,
  ADD COLUMN IF NOT EXISTS alimentacao_tipo text,
  ADD COLUMN IF NOT EXISTS amarracoes_superior text,
  ADD COLUMN IF NOT EXISTS amarracoes_inferior text,
  ADD COLUMN IF NOT EXISTS amarracoes_lateral text,
  ADD COLUMN IF NOT EXISTS vedacao_tipo text,
  ADD COLUMN IF NOT EXISTS vedacao_material text,
  ADD COLUMN IF NOT EXISTS cabeceiras_inicial text,
  ADD COLUMN IF NOT EXISTS cabeceiras_final text,

  ADD COLUMN IF NOT EXISTS motivo_substituicao text,
  ADD COLUMN IF NOT EXISTS tecido_atual text,
  ADD COLUMN IF NOT EXISTS cfm text,
  ADD COLUMN IF NOT EXISTS fornecedor_atual text,
  ADD COLUMN IF NOT EXISTS vida_util text,
  ADD COLUMN IF NOT EXISTS data_ultima_compra text,
  ADD COLUMN IF NOT EXISTS valor_pago text,
  ADD COLUMN IF NOT EXISTS situacao_lonas text,
  ADD COLUMN IF NOT EXISTS previsao_compra text,

  ADD COLUMN IF NOT EXISTS observacoes text,
  ADD COLUMN IF NOT EXISTS acoes text,
  ADD COLUMN IF NOT EXISTS medidas_desenho jsonb;
